"""Create the DocumentsApproval Table

Revision ID: 0d008487c8ee
Revises: 3ef265cdbb17
Create Date: 2022-06-14 19:47:46.339281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d008487c8ee'
down_revision = '3ef265cdbb17'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_approval',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('document_id', postgresql.UUID(), nullable=False),
    sa.Column('approved_by', postgresql.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('awaiting', 'approved', 'rejected', name='document_approval_status_enum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_approval_approved_by'), 'documents_approval', ['approved_by'], unique=False)
    op.create_index(op.f('ix_documents_approval_document_id'), 'documents_approval', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_approval_id'), 'documents_approval', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_approval_id'), table_name='documents_approval')
    op.drop_index(op.f('ix_documents_approval_document_id'), table_name='documents_approval')
    op.drop_index(op.f('ix_documents_approval_approved_by'), table_name='documents_approval')
    op.drop_table('documents_approval')
    # ### end Alembic commands ###

