"""Create the Folders Table

Revision ID: 3ef265cdbb17
Revises: 490177e4c04b
Create Date: 2022-06-14 19:44:25.386352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ef265cdbb17'
down_revision = '490177e4c04b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_folder',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('document_id', postgresql.UUID(), nullable=False),
    sa.Column('folder_id', postgresql.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_folder_document_id'), 'document_folder', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_folder_folder_id'), 'document_folder', ['folder_id'], unique=False)
    op.create_index(op.f('ix_document_folder_id'), 'document_folder', ['id'], unique=True)
    op.create_unique_constraint(None, 'folders', ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='unique')
    op.drop_index(op.f('ix_document_folder_id'), table_name='document_folder')
    op.drop_index(op.f('ix_document_folder_folder_id'), table_name='document_folder')
    op.drop_index(op.f('ix_document_folder_document_id'), table_name='document_folder')
    op.drop_table('document_folder')
    # ### end Alembic commands ###

