"""Create the FormsSchema Table

Revision ID: 47932d016bf0
Revises: 34d78b573f20
Create Date: 2022-06-14 19:30:45.331585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47932d016bf0'
down_revision = '34d78b573f20'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms_schema',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('form_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_schema_id'), 'forms_schema', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_schema_id'), table_name='forms_schema')
    op.drop_table('forms_schema')
    # ### end Alembic commands ###

