"""Create the Documents Table

Revision ID: 7c2139c4ae85
Revises: 0bd097bda7cd
Create Date: 2022-06-14 18:58:45.201282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2139c4ae85'
down_revision = '0bd097bda7cd'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'labels', ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='unique')
    # ### end Alembic commands ###

