"""Create the FormsData Table

Revision ID: d5edcfd3928a
Revises: 47932d016bf0
Create Date: 2022-06-14 19:37:21.147763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5edcfd3928a'
down_revision = '47932d016bf0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms_data',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('document_id', postgresql.UUID(), nullable=False),
    sa.Column('schema_id', postgresql.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['forms_schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_data_document_id'), 'forms_data', ['document_id'], unique=False)
    op.create_index(op.f('ix_forms_data_id'), 'forms_data', ['id'], unique=True)
    op.create_index(op.f('ix_forms_data_schema_id'), 'forms_data', ['schema_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_data_schema_id'), table_name='forms_data')
    op.drop_index(op.f('ix_forms_data_id'), table_name='forms_data')
    op.drop_index(op.f('ix_forms_data_document_id'), table_name='forms_data')
    op.drop_table('forms_data')
    # ### end Alembic commands ###

